// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEaWjwUwgv_UHRq7g7ewcnjA3UfAKvQIM',
    appId: '1:959903382646:web:9611354355458322e3b357',
    messagingSenderId: '959903382646',
    projectId: 'kandaq-c960a',
    authDomain: 'kandaq-c960a.firebaseapp.com',
    storageBucket: 'kandaq-c960a.firebasestorage.app',
    measurementId: 'G-R9TZH6NBHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fsJjzEMe3no5JfBolyKCoLD7A8O4cvs',
    appId: '1:959903382646:android:a8b2de4ccefc13cbe3b357',
    messagingSenderId: '959903382646',
    projectId: 'kandaq-c960a',
    storageBucket: 'kandaq-c960a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7syLcACMVQ-4Ky4tKJPmOguP2n8SKa5g',
    appId: '1:959903382646:ios:f008d8300ac409a1e3b357',
    messagingSenderId: '959903382646',
    projectId: 'kandaq-c960a',
    storageBucket: 'kandaq-c960a.firebasestorage.app',
    iosClientId: '959903382646-4rueu5baugc428ll2dadd16uub6k4rei.apps.googleusercontent.com',
    iosBundleId: 'com.example.kandaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7syLcACMVQ-4Ky4tKJPmOguP2n8SKa5g',
    appId: '1:959903382646:ios:f008d8300ac409a1e3b357',
    messagingSenderId: '959903382646',
    projectId: 'kandaq-c960a',
    storageBucket: 'kandaq-c960a.firebasestorage.app',
    iosClientId: '959903382646-4rueu5baugc428ll2dadd16uub6k4rei.apps.googleusercontent.com',
    iosBundleId: 'com.example.kandaq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEaWjwUwgv_UHRq7g7ewcnjA3UfAKvQIM',
    appId: '1:959903382646:web:2dc96273d3291170e3b357',
    messagingSenderId: '959903382646',
    projectId: 'kandaq-c960a',
    authDomain: 'kandaq-c960a.firebaseapp.com',
    storageBucket: 'kandaq-c960a.firebasestorage.app',
    measurementId: 'G-EMW9HS3W1F',
  );

}