// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Auto-generated by flutterfire configure
import 'features/auth/presentation/login_screen.dart';

void main() async {
  // 1. Required for Firebase & platform channels before runApp
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Initialize Firebase safely
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const KandaqApp());
}

class KandaqApp extends StatelessWidget {
  const KandaqApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'kandaq',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFE65100)),
        useMaterial3: true,
      ),
      home: const AuthGate(),
    );
  }
}

/// 🔐 Auth Gate: Decides which screen to show based on Firebase session
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // 🔹 Still initializing
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // 🔹 User is logged in
        if (snapshot.hasData) {
          return const HomeScreen();
        }

        // 🔹 User is logged out
        return const LoginScreen();
      },
    );
  }
}

/// 🏠 Placeholder Home (for testing successful auth & sign-out)
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;
    
    return Scaffold(
      appBar: AppBar(title: const Text('kandaq')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.restaurant, size: 64, color: Colors.orange),
            const SizedBox(height: 16),
            Text(
              'Welcome, ${user?.email ?? 'User'}',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 24),
            ElevatedButton.icon(
              onPressed: () async {
                await FirebaseAuth.instance.signOut();
                // AuthGate stream will auto-route back to LoginScreen
              },
              icon: const Icon(Icons.logout),
              label: const Text('Sign Out'),
            ),
          ],
        ),
      ),
    );
  }
}